apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  namespace: dataworks
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: slow
  hostPath:
    path: /var/lib/postgresql/data
    type: DirectoryOrCreate